### ISSUE TITLE
lunar.bas has typo in line 20

### ISSUE THREAD

**Issue by Rev-3ng** [GReaperEx/bcg#10]
line 20 has a lowercase 'L' instead of a number '1' inside the TAB() statement.

**Comment by GReaperEx** [comment]
Nice catch! I'll fix it immediately.

**Comment by Rev-3ng** [comment]
hi Marios,

I found that one when I was testing all the Games.
I couldn’t see why it wasn’t working, I just kept getting ?SN ERROR IN 20 on my ALTAIR 680 clone and kept looking at the book and other sources without seeing it.
In the end I only saw it when I was looking at a hex dump of the program and checking each character, one at a time.

cheers,
Mark C.
