### ISSUE TITLE
mine.bas not vintage BASIC

### ISSUE THREAD

**Issue by Rev-3ng** [GReaperEx/bcg#3]
this program does not appear to be a vintage BASIC file. is it supposed to be ?

**Comment by GReaperEx** [comment]
I'm not sure about this one. If I can find out for a fact that it doesn't appear in the book, I'll remove it.

**Comment by Rev-3ng** [comment]
it's pretty obvious looking at the code.
1. No BASIC line numbers. I don't know of any vintage BASICs that don't have line numbers.
2. use of a mouse in line 110-111 in the listing.
3. use of foreground and background colour in line 313-314.
4. use of events in line 485.
5. use of procedure declarations.
I've checked 101 BASIC Computer Games and More BASIC Computer Games and it's not in either of those books.

**Comment by GReaperEx** [comment]
Fair enough. It will be removed.
