### ISSUE TITLE
superstartrek.bas has typo

### ISSUE THREAD

**Issue by Rev-3ng** [GReaperEx/bcg#8]
line 1150 has a typo, ie. '120' near the end of the line. It should be '100'.
The original BASIC Computer Games book shows:
1150 IFG(Q1,Q2)<200THENG(Q1,Q2)=G(Q1,Q2)+100:K9=K9+1

**Comment by GReaperEx** [comment]
Indeed, it looks like a `120` but it actually is `100`. Thanks.
