### ISSUE TITLE
stockmarket.bas causes ?TM ERROR

### ISSUE THREAD

**Issue by Rev-3ng** [GReaperEx/bcg#9]
line 658 causes '?TM ERROR IN 658' on 8K ALTAIR 680 BASIC.
other published versions of this add a ';' before '-C5' or place -C5 in parethesis. ie:
658 PRINT "YOU HAVE USED $";-C5" MORE THAN YOU HAVE." 
or
658 PRINT "YOU HAVE USED $"(-C5)" MORE THAN YOU HAVE."

this needs to be confirmed and tested in other versions of 8K BASIC as I have only tested it on a port of ALTAIR BASIC I am developing.

**Comment by GReaperEx** [comment]
Hmm, again, should I change it if it's as it was in the original?...

**Comment by Rev-3ng** [comment]
I guess this depends on your definition of 'original'. what is the source of your files, and what systems should they run on ?
Also would you expect anyone using the files to have to make corrections before the program runs. If they typed it from a real manual then they would most likely have to have fixed some lines or altered some lines to run on their specific system.

In my 1975 printing of 101 BASIC Computer Games it has the extra ';' before 'C5' in line 658.
refer to scans below. BTW, that program was called 'STOCK' in this earlier version, probably a limitation of the system it was created on.
[DIGITAL.101.COVER.PDF](https://github.com/GReaperEx/bcg/files/9276533/DIGITAL.101.COVER.PDF)
[STOCK.BAS.101.PDF](https://github.com/GReaperEx/bcg/files/9276534/STOCK.BAS.101.PDF)

In my later copy from BASIC Computer Games - TRS-80 Edition (~1978) the 'C5' was enclosed in parenthesis in line 1560 of a renumbered version of that program called 'STOCK MARKET'.
[STOCKMARKET.BAS.TRS80.PDF](https://github.com/GReaperEx/bcg/files/9276537/STOCKMARKET.BAS.TRS80.PDF)

Both of those variations work on my ALTAIR 680 port, but not the version in BASIC Computer Games - Microcomputer edition without ';' or parenthesis. It's up to you whether to amend the files, or perhaps include a note about other versions.

regards,
Mark.
